import Link from "next/link";

const CAL_URL = "https://cal.com/alameenpd/quick-chat";
const DISCORD_URL = "https://discord.gg/QJBCcB7bF";

export default function PapersPage() {
  return (
    <main className="papers-page">
      <style>{styles}</style>

      <nav className="top-nav">
        <Link href="/" className="brand">Bad Theory Labs</Link>
        <div className="nav-links">
          <Link href="/#research">Research</Link>
          <Link href="/#products">Products</Link>
          <Link href="/reasoning-gap">Reasoning Gap</Link>
          <Link href="/papers" aria-current="page">Papers</Link>
          <Link href="/brief">Brief</Link>
          <Link href="/whitepaper">Whitepaper</Link>
          <Link href="/stats">Stats</Link>
          <Link href="/contact">Contact</Link>
        </div>
        <div className="nav-cta">
          <a href={DISCORD_URL} target="_blank" rel="noreferrer">Join community</a>
          <a href={CAL_URL} target="_blank" rel="noreferrer" className="solid">Schedule call</a>
        </div>
      </nav>

      <section className="hero">
        <p className="eyebrow">Research</p>
        <h1>The Compression Program</h1>
        <p>Bad Theory Labs - Internal Research Program</p>
      </section>

      <section className="paper-wrap">
        <article className="paper">
          <header>
            <p className="paper-meta">Bad Theory Labs - Internal Research Program</p>
            <h2>The Compression Program</h2>
            <p className="status">Active - Program opened April 2026 · Lead: Al-ameen · Lab: Bad Theory Labs, Lagos</p>
          </header>

          <h3>Thesis</h3>
          <p><strong>Intelligence is compression.</strong></p>
          <p>
            Not metaphorically - mechanically. To perceive is to compress sensory input into representations that
            preserve what is useful and discard what is not. To reason is to compress those representations further,
            into structure that supports prediction, transfer, and counterfactual inference. To act is to compress a
            goal and a world-model into a decision under uncertainty.
          </p>
          <p>
            This is not a new observation. Shannon formalized it. Kolmogorov sharpened it. Hinton built careers
            adjacent to it. What the field has not done is take it seriously as a design principle - as the thing you
            actually optimize for, rather than a property that sometimes emerges from optimizing for something else.
          </p>
          <p>
            What we call reasoning in current systems is better described as pattern completion at scale: shallow
            compression, fast and brittle, that fails precisely when the test distribution requires a step the training
            distribution never took. We are investigating whether there exists a structurally different regime - deep
            compression - in which representations are not just statistically compact but causally structured: stable
            under intervention, not just under observation.
          </p>
          <p>
            The Compression Program is Bad Theory Labs&apos; attempt to establish rigorous empirical evidence for this
            distinction, and to build the training methodology that follows from it.
          </p>

          <h3>The Core Bet</h3>
          <p>
            The field has been optimizing the wrong objective for a decade. Next-token prediction induces compression
            as a side effect of generalization pressure - incidental, uncontrolled, and shallow by default. Our bet is
            that treating compression as a primary objective produces qualitatively different internal representations:
            ones that encode generating structure rather than surface statistics.
          </p>
          <p>
            Our further hypothesis - which we intend to test, not assume - is that representations built under a
            genuine compression objective will tend toward causal structure. Not because causality is explicitly
            supervised, but because the shortest sufficient explanation of a distribution generated by a causal process
            is the causal process.
          </p>
          <p>
            At sufficient compression depth, we expect behavior that looks like reasoning: counterfactual stability,
            systematic generalization, structured transfer. This is falsifiable by design.
          </p>

          <h3>Key Definitions</h3>
          <p>
            <strong>Compression Depth:</strong> the minimum number of sequential abstraction steps required to reduce a
            problem instance to its minimal sufficient description. A depth-1 task is lookup/memorization. Depth-2 is
            learning the rule generating that lookup. Depth-3 is learning the meta-rule generating the rule. A model&apos;s
            effective compression depth is the maximum task depth where it still generalizes OOD.
          </p>
          <p>
            <strong>Causal Minimality:</strong> a representation is causally minimal if it encodes generating causal
            structure rather than a compact summary of surface correlations. Formally, representation R of
            distribution P is causally minimal if R supports inference under interventional queries P(Y | do(X)), not
            just observational P(Y | X).
          </p>

          <h3>Workstreams</h3>
          <h4>01 - Compression as Objective</h4>
          <p>
            Current systems are trained to predict. Compression is incidental. This workstream asks: what if
            compression were the loss?
          </p>
          <p>
            Grounding: two-part MDL objective, minimize L(model) + L(data | model). Key departure from prior MDL work:
            not MDL as a regularizer on prediction, but replacement of prediction objective itself.
          </p>
          <p><strong>Key questions:</strong></p>
          <ul>
            <li>How should L(model) be operationalized in neural networks (bits-back, PAC-Bayes, variational proxies)?</li>
            <li>Does compression-as-objective produce more causally structured representations than prediction-as-objective?</li>
            <li>Is compression depth monotonically related to OOD generalization, or does it show phase transition behavior?</li>
          </ul>

          <h4>02 - The Reasoning Gap</h4>
          <p>
            This workstream asks whether current AI is reasoning or pattern completion, as an empirical question with a
            designed answer.
          </p>
          <p>
            Hypothesis: genuine reasoning requires representations supporting interventional inference, not only
            observational inference. P(Y | X = x) and P(Y | do(X = x)) are different quantities.
          </p>
          <p><strong>Key questions:</strong></p>
          <ul>
            <li>Can we build a benchmark that provably separates observational and interventional reasoning?</li>
            <li>What is the quantitative reasoning gap for frontier models?</li>
            <li>Does the gap close with scale, or is it objective/architecture dependent?</li>
            <li>Is there a compression-depth threshold where the gap closes?</li>
          </ul>

          <h3>How They Relate</h3>
          <p>01 and 02 are two ends of the same proof.</p>
          <p>01 asks: if we compress correctly, what structure emerges?</p>
          <p>02 asks: what structure must exist for genuine reasoning?</p>
          <p><strong>Central hypothesis: the answer to both is causal structure.</strong></p>
          <p>
            If 01 shows compression-as-objective produces causally structured representations, and 02 shows causal
            structure is what reasoning requires, then compression is the mechanism and reasoning is what emerges.
          </p>

          <h3>What Success Looks Like</h3>
          <ul>
            <li>Benchmark from 02 adopted as a standard for measuring genuine reasoning.</li>
            <li>Training objective from 01 that outperforms next-token prediction on that benchmark at matched compute.</li>
            <li>At least one surprising result predicted by compression framing and validated empirically.</li>
            <li>Internal eval/training/probing infrastructure for all future Bad Theory Labs models.</li>
          </ul>

          <h3>What This Is Not</h3>
          <p>
            This is not benchmark chasing, prompting GPT-4 and calling it research, or capabilities theater. This is a
            mechanistic research program that can fail, and if it fails, that failure is also a real result.
          </p>

          <h3>The Compression Program - Experiment Designs</h3>
          <p className="paper-submeta">Bad Theory Labs</p>

          <h4>Workstream 01 - Compression as Objective</h4>
          <p>
            Core claim: if compression is the primary objective, representations will be structurally different and
            better than those produced by prediction-as-objective.
          </p>

          <h5>Experiment 1.1 - MDL as Loss</h5>
          <p><strong>Hypothesis:</strong> MDL-trained models recover generating structure; cross-entropy models learn brittle correlations.</p>
          <p><strong>Setup:</strong> synthetic dataset from known generating program; matched transformer pair (cross-entropy baseline vs MDL objective).</p>
          <p><strong>Measurement:</strong> OOD generalization, representation alignment via probes, and held-out description length.</p>
          <p><strong>Expected:</strong> MDL condition generalizes better and aligns with generating variables.</p>
          <p><strong>Falsification:</strong> equal OOD performance implies no structural benefit beyond implicit compression in prediction.</p>

          <h5>Experiment 1.2 - Compression Depth vs Generalization</h5>
          <p><strong>Hypothesis:</strong> monotonic relation between compression depth and OOD generalization.</p>
          <p><strong>Setup:</strong> depth-1 through depth-5 curriculum with shared surface format and increasing abstraction demands.</p>
          <p><strong>Measurement:</strong> OOD accuracy vs depth, representation probing, and transfer from deep to shallow tasks.</p>
          <p><strong>Falsification:</strong> non-monotonic behavior implies compression depth is not the sole explanatory variable.</p>

          <h5>Experiment 1.3 - Representation Causality</h5>
          <p><strong>Hypothesis:</strong> compression objective induces causal representations without explicit causal supervision.</p>
          <p><strong>Setup:</strong> synthetic SCM with known graph; compare cross-entropy and MDL training.</p>
          <p><strong>Measurement:</strong> probe accuracy for parents/directions and counterfactual prediction under forced interventions.</p>
          <p><strong>Falsification:</strong> parity between conditions indicates compression is not the causal-representation mechanism.</p>

          <h4>Workstream 02 - The Reasoning Gap</h4>
          <p>
            Core claim: current AI is primarily pattern completion, not reasoning. These are structurally different and
            empirically separable.
          </p>

          <h5>Experiment 2.1 - The Separation Benchmark</h5>
          <p><strong>Hypothesis:</strong> class A pattern tasks and class B causal tasks can share format while requiring different structure.</p>
          <p><strong>Setup:</strong> evaluate frontier models (GPT-4o, Claude, Gemini) on both classes.</p>
          <p><strong>Measurement:</strong> class A vs class B accuracy, model-size correlation, and causal failure taxonomy.</p>
          <p><strong>Expected:</strong> near-ceiling class A, substantial class B failures, weak scale-to-causal-performance relation.</p>

          <h5>Experiment 2.2 - Observation vs Intervention</h5>
          <p><strong>Hypothesis:</strong> models passing observational tasks fail intervention queries beyond what difficulty alone explains.</p>
          <p><strong>Setup:</strong> known causal graph; query both P(Z | X=x) and P(Z | do(X=x)).</p>
          <p><strong>Measurement:</strong> observational accuracy, interventional accuracy, and their delta as operationalized reasoning gap.</p>
          <p><strong>Falsification:</strong> if scale closes the gap, strong thesis version must be revised.</p>

          <h5>Experiment 2.3 - The Phase Transition</h5>
          <p><strong>Hypothesis:</strong> reasoning emerges at threshold compression depth d*, as a phase transition, not smooth trend.</p>
          <p><strong>Setup:</strong> evaluate depth-trained models from 1.2 on class-B and intervention tasks from 2.1/2.2.</p>
          <p><strong>Measurement:</strong> reasoning-gap score vs depth; detect non-linearity and representation change at d*.</p>
          <p><strong>Falsification:</strong> linear improvements imply gradual enablement, not discrete emergence.</p>

          <h3>The Connection</h3>
          <ul>
            <li>1.1 establishes that compression objective changes representations.</li>
            <li>1.2 establishes that compression depth predicts generalization.</li>
            <li>1.3 establishes that compression produces causal representations.</li>
            <li>2.1 establishes reasoning gap is real and measurable.</li>
            <li>2.2 operationalizes reasoning gap formally (observation vs intervention).</li>
            <li>2.3 connects both workstreams (compression depth predicts reasoning gap).</li>
          </ul>
          <p><strong>Together: compression is the mechanism, reasoning emerges at depth.</strong></p>

          <h3>Order of Execution</h3>
          <ol>
            <li>Start with 2.1 (benchmark first).</li>
            <li>Run 1.1 in parallel (small compute, quick signal).</li>
            <li>Run 1.2 and 1.3 after early 1.1 results.</li>
            <li>Run 2.2 once 2.1 benchmark is validated.</li>
            <li>Run 2.3 last as synthesis.</li>
          </ol>

          <h3>What a Paper Looks Like</h3>
          <p><strong>Paper 1:</strong> The Reasoning Gap Benchmark (2.1 + 2.2). Claim: rigorous empirical distinction between pattern completion and reasoning.</p>
          <p><strong>Paper 2:</strong> Compression as Mechanism (1.1 + 1.2 + 1.3 + 2.3). Claim: compression-as-objective produces causal representations, and reasoning emerges at sufficient depth.</p>

          <blockquote>
            &ldquo;The field has been teaching systems to predict the world. We are trying to build systems that understand
            it. The difference is not scale. It is the objective.&rdquo;
          </blockquote>
          <p className="paper-submeta">Bad Theory Labs, Lagos - April 2026</p>
        </article>
      </section>
    </main>
  );
}

const styles = `
:root { --bg:#fafaf9; --surface:#f3f2ef; --border:#e8e6e1; --ink:#0e0d0c; --body:#5c5954; --faint:#9c9890; }
.papers-page { min-height:100vh; background:var(--bg); color:var(--ink); }
.top-nav { position:sticky; top:0; z-index:20; height:58px; border-bottom:1px solid var(--border); background:rgba(250,250,249,.88); backdrop-filter:blur(18px); display:flex; align-items:center; justify-content:space-between; padding:0 28px; }
.brand { font-family:var(--font-d); font-size:22px; color:var(--ink); text-decoration:none; }
.nav-links, .nav-cta { display:flex; gap:16px; align-items:center; }
.nav-links a, .nav-cta a { text-decoration:none; color:var(--body); font-family:var(--font-s); font-size:13px; }
.nav-cta .solid { background:var(--ink); color:var(--bg); padding:8px 14px; border-radius:8px; }
.hero { max-width:1080px; margin:0 auto; padding:72px 28px 36px; border-bottom:1px solid var(--border); }
.eyebrow { font-family:var(--font-m); text-transform:uppercase; letter-spacing:.12em; color:var(--faint); font-size:11px; margin-bottom:10px; }
.hero h1 { font-family:var(--font-d); font-size:clamp(42px,6vw,70px); letter-spacing:-.03em; line-height:1.02; margin-bottom:8px; }
.hero p { color:var(--body); }
.paper-wrap { max-width:1080px; margin:0 auto; padding:30px 28px 70px; }
.paper { max-width:920px; border:1px solid var(--border); border-radius:16px; background:var(--surface); padding:24px; }
.paper-meta { font-family:var(--font-m); text-transform:uppercase; letter-spacing:.12em; font-size:10px; color:var(--faint); margin-bottom:8px; }
.paper h2 { font-family:var(--font-d); font-size:50px; letter-spacing:-.03em; line-height:1.02; margin-bottom:8px; }
.status { color:var(--faint); font-size:13px; margin-bottom:16px; }
.paper h3 { font-family:var(--font-d); font-size:31px; margin:26px 0 10px; }
.paper h4 { font-family:var(--font-d); font-size:24px; margin:20px 0 8px; }
.paper h5 { font-family:var(--font-m); text-transform:uppercase; letter-spacing:.08em; color:var(--ink); font-size:12px; margin:16px 0 6px; }
.paper p { color:var(--body); line-height:1.8; margin-bottom:10px; }
.paper ul, .paper ol { margin:6px 0 0 18px; color:var(--body); line-height:1.8; }
.paper-submeta { font-family:var(--font-m); font-size:11px; color:var(--faint); letter-spacing:.06em; text-transform:uppercase; margin-top:8px; }
blockquote { margin-top:24px; border-left:2px solid var(--border); padding-left:14px; color:var(--ink); font-family:var(--font-d); font-size:24px; letter-spacing:-.01em; }
@media (max-width: 900px) {
  .nav-links { display:none; }
  .top-nav { padding:0 16px; }
  .hero, .paper-wrap { padding-left:16px; padding-right:16px; }
  .paper h2 { font-size:40px; }
}
`;
